# Kafka Settings
kafka:
  bootstrap_servers: "redpanda:9092"
  topic: "agent-observations"
  group_id: "marl_group"

# Cassandra Settings
cassandra:
  contact_points: ["cassandra"]
  port: 9042
  keyspace: "marl_data"
  table: "env_observations"

# MLflow Settings
mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "MARL-Experiment"

# Ray Cluster
ray:
  dashboard_host: "0.0.0.0"
  dashboard_port: 8265
  serve_port: 8000

# Environment Settings
environment:
  name: "GridWorldMultiAgent"
  num_agents: 2
  grid_size: 5
  episode_limit: 50

# PPO Agent Settings
agent:
  framework: "torch"
  lr: 0.0003
  gamma: 0.99
  lambda: 0.95
  clip_param: 0.2
  train_batch_size: 4000
  rollout_fragment_length: 200
  num_workers: 1
  num_envs_per_worker: 1

# Model Output
output:
  model_dir: "./saved_model/"
  metrics_file: "./training_metrics.json"
